# -*- coding: utf-8 -*-
"""inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ethA2df26QkRNoYJhH7AaGEo_pOT0Wo1
"""

import joblib
import json
import numpy as np
import pandas as pd

# Load the model from SageMaker's model directory
model = joblib.load("/opt/ml/model/model.pkl")

def input_fn(request_body, request_content_type):
    """Process input data"""
    if request_content_type == 'application/json':
        # Parse the JSON input
        data = json.loads(request_body)

        # Convert to DataFrame to match our training format
        if isinstance(data, list):
            df = pd.DataFrame(data)
        else:
            df = pd.DataFrame([data])

        # Ensure we have all required features
        required_features = ['Entity', 'Code', 'Year']  # Add all required features
        if not all(feat in df.columns for feat in required_features):
            raise ValueError("Missing required features")

        return df
    raise ValueError(f"Unsupported content type: {request_content_type}")

def predict_fn(input_data, model):
    """Make predictions"""
    try:
        predictions = model.predict(input_data)
        return predictions
    except Exception as e:
        print(f"Prediction error: {str(e)}")
        raise

def output_fn(prediction, response_content_type):
    """Format the prediction output"""
    if response_content_type == 'application/json':
        return json.dumps({
            'predictions': prediction.tolist(),
            'status': 'success'
        })
    raise ValueError(f"Unsupported content type: {response_content_type}")